from __future__ import annotations

import hashlib
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from scripts import probe_smoke_environment as probe


EVIDENCE_PATH = probe.PROJECT_ROOT / "results" / "smoke_environment.json"
INPUT_PATH = probe.PROJECT_ROOT / "requirements-smoke.in"


class SmokeEnvironmentUnitTests(unittest.TestCase):
    def test_expected_lane_is_pinned_and_separate_from_m6(self) -> None:
        self.assertEqual(probe.LANE_ID, "phase-a-windows-unsloth-trl024")
        self.assertEqual(probe.EXPECTED_PACKAGES["trl"], "0.24.0")
        self.assertEqual(probe.EXPECTED_PACKAGES["triton-windows"], "3.6.0.post26")
        self.assertNotIn("1.8.0", probe.EXPECTED_PACKAGES.values())

    def test_input_and_lock_pin_the_supported_windows_cuda_artifacts(self) -> None:
        input_text = INPUT_PATH.read_text(encoding="utf-8")
        lock_text = probe.LOCK_PATH.read_text(encoding="utf-8")
        required_fragments = (
            "torch-2.11.0%2Bcu128-cp312-cp312-win_amd64.whl#sha256=7c78215c",
            "torchvision-0.26.0%2Bcu128-cp312-cp312-win_amd64.whl#sha256=8c0d1c4f",
            "xformers-0.0.35-py39-none-win_amd64.whl#sha256=57381ce3",
            "triton_windows-3.6.0.post26-cp312-cp312-win_amd64.whl#sha256=189d8c57",
            "unsloth[windows]==2026.8.18",
            "transformers==5.5.0",
            "trl==0.24.0",
            "pip==25.0.1",
            "-e .",
        )
        for fragment in required_fragments:
            with self.subTest(fragment=fragment):
                self.assertIn(fragment, input_text)
        self.assertNotIn("trl==1.8.0", input_text)
        self.assertNotIn("triton-windows==3.7", input_text)
        self.assertTrue(lock_text.startswith("# This file was autogenerated by uv"))
        self.assertIn("\n-e .\n", lock_text)

    def test_sha256_file_hashes_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "payload.bin"
            path.write_bytes(b"locked environment\n")
            self.assertEqual(
                probe.sha256_file(path),
                hashlib.sha256(b"locked environment\n").hexdigest(),
            )

    def test_bounded_capture_preserves_the_child_result_tail(self) -> None:
        value = "x" * (probe.MAX_CAPTURE_CHARS + 10) + probe.CHILD_MARKER + "{}"
        bounded = probe._bounded(value)
        self.assertLessEqual(
            len(bounded), probe.MAX_CAPTURE_CHARS + len("...[truncated]\n")
        )
        self.assertTrue(bounded.endswith(probe.CHILD_MARKER + "{}"))

    def test_capture_redacts_common_environment_credentials(self) -> None:
        raw = (
            "HF_TOKEN=hf_abcdefghijklmnopqrstuvwxyz\n"
            "Authorization: Bearer abc.def.ghi\n"
            "api_key=plain-secret\n"
        )
        sanitized = probe._sanitize_capture(raw)
        self.assertNotIn("hf_abcdefghijklmnopqrstuvwxyz", sanitized)
        self.assertNotIn("abc.def.ghi", sanitized)
        self.assertNotIn("plain-secret", sanitized)
        self.assertIn("[REDACTED]", sanitized)

    def test_missing_executable_is_recorded_as_failure(self) -> None:
        result = probe._run_command(
            ["codex-definitely-missing-smoke-executable-7f1f"],
            timeout_seconds=1,
        )
        self.assertEqual(result["status"], "failed")
        self.assertIsNone(result["returncode"])
        self.assertIn("FileNotFoundError", result["stderr_tail"])

    def test_import_child_receives_offline_sanitized_environment(self) -> None:
        command_result = {
            "status": "failed",
            "returncode": 1,
            "elapsed_seconds": 0.1,
            "stdout_tail": "",
            "stderr_tail": "test failure",
        }
        with (
            patch.dict(
                os.environ,
                {
                    "HF_TOKEN": "hf_should_not_escape",
                    "TEST_API_KEY": "should-not-escape",
                },
                clear=False,
            ),
            patch.object(probe, "_run_command", return_value=command_result) as runner,
        ):
            result = probe._run_import_probe(1)

        environment = runner.call_args.kwargs["environment"]
        self.assertNotIn("HF_TOKEN", environment)
        self.assertNotIn("TEST_API_KEY", environment)
        self.assertEqual(environment["HF_HUB_OFFLINE"], "1")
        self.assertEqual(environment["TRANSFORMERS_OFFLINE"], "1")
        self.assertEqual(environment["HF_DATASETS_OFFLINE"], "1")
        self.assertTrue(result["environment_policy"]["sensitive_named_variables_removed"])

    def test_atomic_json_writer_is_strict_and_round_trips(self) -> None:
        payload = {"schema_version": 1, "status": "passed", "value": [1, 2]}
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "nested" / "evidence.json"
            probe.write_json_atomic(payload, output)
            restored = json.loads(
                output.read_text(encoding="utf-8"),
                parse_constant=lambda value: self.fail(f"non-finite {value}"),
            )
            self.assertEqual(restored, payload)
            self.assertEqual(list(output.parent.glob("*.tmp")), [])

    def test_report_requires_exact_packages_cuda_and_parser(self) -> None:
        report = {
            "packages": dict(probe.EXPECTED_PACKAGES),
            "lock": {"matches_configured_sha256": True},
            "environment_consistency": {"status": "passed"},
            "dependency_check": {"status": "passed"},
            "source": {"git_worktree_clean": True},
            "nvidia_smi": {"gpus": [{"name": "test GPU"}]},
            "import_probe": {
                "status": "passed",
                "details": {
                    "imports": {"agent.parser": True},
                    "torch": {"cuda_available": True, "device_count": 1},
                },
            },
        }
        self.assertTrue(probe._report_passes(report))

        for mutation in (
            "packages",
            "lock",
            "environment",
            "git",
            "cuda",
            "device_count",
            "parser",
        ):
            with self.subTest(mutation=mutation):
                changed = json.loads(json.dumps(report))
                if mutation == "packages":
                    changed["packages"]["trl"] = "1.8.0"
                elif mutation == "lock":
                    changed["lock"]["matches_configured_sha256"] = False
                elif mutation == "environment":
                    changed["environment_consistency"]["status"] = "failed"
                elif mutation == "git":
                    changed["source"]["git_worktree_clean"] = False
                elif mutation == "cuda":
                    changed["import_probe"]["details"]["torch"]["cuda_available"] = False
                elif mutation == "device_count":
                    changed["import_probe"]["details"]["torch"]["device_count"] = 2
                else:
                    changed["import_probe"]["details"]["imports"]["agent.parser"] = False
                self.assertFalse(probe._report_passes(changed))

    def test_checked_in_evidence_matches_the_current_lock_and_sources(self) -> None:
        evidence = json.loads(
            EVIDENCE_PATH.read_text(encoding="utf-8"),
            parse_constant=lambda value: self.fail(f"non-finite {value}"),
            object_pairs_hook=self._unique_object,
        )
        self.assertEqual(evidence["schema_version"], probe.SCHEMA_VERSION)
        self.assertEqual(evidence["lane_id"], probe.LANE_ID)
        self.assertEqual(evidence["status"], "passed")
        self.assertEqual(evidence["packages"], probe.EXPECTED_PACKAGES)
        self.assertTrue(probe._report_passes(evidence))
        self.assertEqual(
            evidence["lock"]["sha256"], probe.sha256_file(probe.LOCK_PATH)
        )
        self.assertEqual(
            evidence["lock"]["configured_sha256"],
            probe._configured_lock_sha256(),
        )
        self.assertTrue(evidence["lock"]["matches_configured_sha256"])
        self.assertEqual(
            evidence["scope"],
            {
                "huggingface_offline_mode_enforced_for_import_child": True,
                "m6_environment_factory_in_scope": False,
                "model_repository_access": "not_requested_by_probe",
                "model_weights_loaded": False,
            },
        )
        self.assertEqual(
            set(evidence["source"]["file_sha256"]), set(probe.SOURCE_PATHS)
        )
        for relative_path, expected_hash in evidence["source"]["file_sha256"].items():
            self.assertEqual(
                expected_hash,
                probe.sha256_file(probe.PROJECT_ROOT / relative_path),
                relative_path,
            )

    @staticmethod
    def _unique_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
        result: dict[str, object] = {}
        for key, value in pairs:
            if key in result:
                raise AssertionError(f"duplicate JSON key: {key}")
            result[key] = value
        return result


if __name__ == "__main__":
    unittest.main()
